#Use root/example as user/password credentials
version: "3.1"

services:
    popUpTeamDb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: popUpTeamDb
            MYSQL_ROOT_PASSWORD: 671885a1
        volumes:
            - "popUpTeam-mysql-data:/var/lib/mysql"

    backend:
        build: ./
        restart: always
        ports:
            - 9080:3001
        volumes:
            - "app-data:/app/public/images/"

    adminer:
        image: adminer
        restart: always
        ports:
            - 9081:8080

volumes:
    popUpTeam-mysql-data:
    app-data:
